// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC4TfDM4RoHkDnogdP_gPwJ1CtLkQc_xg',
    appId: '1:514105496890:web:a4d37f6aefa8465f1e2c03',
    messagingSenderId: '514105496890',
    projectId: 'jamboo-ee445',
    authDomain: 'jamboo-ee445.firebaseapp.com',
    storageBucket: 'jamboo-ee445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvDnUwPF_zRxuUTi4XdW0Xbbn6cKUgzg',
    appId: '1:514105496890:android:c4058674fdbe65161e2c03',
    messagingSenderId: '514105496890',
    projectId: 'jamboo-ee445',
    storageBucket: 'jamboo-ee445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79pNGi0kajIMrDLzmXQ7Ivg7OLeJKfJE',
    appId: '1:514105496890:ios:f157cf411505af8d1e2c03',
    messagingSenderId: '514105496890',
    projectId: 'jamboo-ee445',
    storageBucket: 'jamboo-ee445.firebasestorage.app',
    iosClientId: '514105496890-bgb83l5rb8df31hsg0ir8q88c76itb2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamboo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79pNGi0kajIMrDLzmXQ7Ivg7OLeJKfJE',
    appId: '1:514105496890:ios:f157cf411505af8d1e2c03',
    messagingSenderId: '514105496890',
    projectId: 'jamboo-ee445',
    storageBucket: 'jamboo-ee445.firebasestorage.app',
    iosClientId: '514105496890-bgb83l5rb8df31hsg0ir8q88c76itb2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamboo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC4TfDM4RoHkDnogdP_gPwJ1CtLkQc_xg',
    appId: '1:514105496890:web:f4252e522bb466481e2c03',
    messagingSenderId: '514105496890',
    projectId: 'jamboo-ee445',
    authDomain: 'jamboo-ee445.firebaseapp.com',
    storageBucket: 'jamboo-ee445.firebasestorage.app',
  );
}
